backend:
  name: git-gateway
  branch: master # Branch to update (optional; defaults to master)
  
# This line should *not* be indented
publish_mode: editorial_workflow

# backend:
#   name: github
#   repo: OmahaCode/cloud

media_folder: src/images
public_folder: src/images/uploads

collections:
  - name: blog
    label: Blog
    folder: src/pages/blog
    create: true
    fields:
      - { name: path, label: Path }
      - { name: date, label: Date, widget: datetime }
      - { name: title, label: Title }
      - { name: body, label: Body, widget: markdown }